### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by mwildehahn** [serverless/serverless-graphql-blog#10]
Running into several issues trying to get this example running. Following along with the instructions I get:

```
$ serverless project install serverless-graphql-blog
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.0
`-------'

Serverless: Installing Serverless Project "serverless-graphql-blog"...
Serverless: Downloading project and installing dependencies...
/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: This plugin could not be found: serverless-optimizer-plugin
    at new ServerlessError (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Error.js:17:11)
    at Serverless._loadPlugins (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:293:17)
    at Serverless.loadProjectPlugins (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at /Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/actions/ProjectInstall.js:213:24
From previous event:
    at ProjectInstall._initProject (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/actions/ProjectInstall.js:208:27)
From previous event:
    at ProjectInstall.installProject (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/actions/ProjectInstall.js:110:12)
From previous event:
    at /Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/bin/serverless:19:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Object.<anonymous> (/Users/mhahn/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

trying to run `npm install` within the cloned repo results in:

```
$ npm install
serverless-graphql-blog@0.0.1 /Users/mhahn/labs/serverless-graphql-blog
└── (empty)

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/mhahn/.nvm/versions/node/v5.9.1/bin/node" "/Users/mhahn/.nvm/versions/node/v5.9.1/bin/npm" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.8.3
npm ERR! path /Users/mhahn/labs/serverless-graphql-blog/node_modules/.staging/serverless-graphql-blog-1c4b69c2
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/mhahn/labs/serverless-graphql-blog/node_modules/.staging/serverless-graphql-blog-1c4b69c2' -> '/Users/mhahn/labs/serverless-graphql-blog'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/mhahn/labs/serverless-graphql-blog/node_modules/.staging/serverless-graphql-blog-1c4b69c2' -> '/Users/mhahn/labs/serverless-graphql-blog'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/mhahn/.nvm/versions/node/v5.9.1/bin/node" "/Users/mhahn/.nvm/versions/node/v5.9.1/bin/npm" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.8.3
npm ERR! path npm-debug.log.3086759565
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3086759565'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3086759565'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mhahn/labs/serverless-graphql-blog/npm-debug.log
npm ERR! code 1
```

relevant versions:

```
node: v5.9.1
npm: 3.8.3
serverless: 0.5.0
```

**Comment by kevinold** [comment]
@mhahn I have not updated for 0.4 or 0.5 but hope to soon.

**Comment by mwildehahn** [comment]
ok that makes sense. thanks
