### ISSUE TITLE
Installation is broken on a fresh install of npm/serverless (mac osx)

### ISSUE THREAD

**Issue by marksteele** [serverless/serverless-graphql-blog#12]
```
serverless project install serverless-graphql-blog
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.1
`-------'

Serverless: Installing Serverless Project "serverless-graphql-blog"...
Serverless: Downloading project and installing dependencies...
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: This plugin could not be found: serverless-optimizer-plugin
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:293:17)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at /usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:213:24
From previous event:
    at ProjectInstall._initProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:208:27)
From previous event:
    at ProjectInstall.installProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:110:12)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by marksteele** [comment]
Also tried on linux:

```
[root@vagrant ~]# serverless project install serverless-graphql-blog
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.1
`-------'

Serverless: Installing Serverless Project "serverless-graphql-blog"...
Serverless: Downloading project and installing dependencies...
/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Class extends value #<Serverless> is not a function or null
    at module.exports.ServerlessPlugin.browserify._this.config.requires.map._this.config.plugins.map._this.config.transforms.map._this.config.exclude.forEach._this.config.ignore.forEach._generateIncludePaths (/root/serverless-graphql-blog/node_modules/serverless-optimizer-plugin/index.js:21:37)
    at Serverless._loadPlugins (/usr/lib/node_modules/serverless/lib/Serverless.js:286:25)
    at Serverless.loadProjectPlugins (/usr/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at /usr/lib/node_modules/serverless/lib/actions/ProjectInstall.js:213:24
From previous event:
    at ProjectInstall._initProject (/usr/lib/node_modules/serverless/lib/actions/ProjectInstall.js:208:27)
From previous event:
    at ProjectInstall.installProject (/usr/lib/node_modules/serverless/lib/actions/ProjectInstall.js:110:12)
From previous event:
    at /usr/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /usr/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/usr/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/usr/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/usr/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /usr/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
[root@vagrant ~]# 
```

**Comment by balmasi** [comment]
Not just that project.

Just tried with `serverless-starter` project and that fails too :(

**Comment by marksteele** [comment]
Think this was version issue, closing for now...
