### ISSUE TITLE
Error loading request plugin

### ISSUE THREAD

**Issue by selvameenal** [serverless/serverless-graphql-blog#13]
I did:

npm install request --save

Then added it to s-project.json:
"plugins": ["request"]

When I do server less dash deploy, I get the following error:
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

Error: options.uri is a required argument
    at Request.init (/Users/Meenals/workspace/lambdas/RegistrationLogin/node_modules/request/request.js:246:31)
    at new Request (/Users/Meenals/workspace/lambdas/RegistrationLogin/node_modules/request/request.js:142:8)
    at request (/Users/Meenals/workspace/lambdas/RegistrationLogin/node_modules/request/index.js:55:10)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:291:25)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:245:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:76:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:72:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

When loading the plugin itself, it is trying to create a new Request object, which in turn is erroring out, since the required variables are niot present

**Comment by selvameenal** [comment]
Added in the wrong place. Opened it under server less. Closing it now
